# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/Mardel/clion-2018.1.2/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/Mardel/clion-2018.1.2/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Mardel/ModulesTek2/C++/cpp_indie_studio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Mardel/ModulesTek2/C++/cpp_indie_studio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/Mardel/clion-2018.1.2/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Mardel/ModulesTek2/C++/cpp_indie_studio/CMakeFiles /home/Mardel/ModulesTek2/C++/cpp_indie_studio/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Mardel/ModulesTek2/C++/cpp_indie_studio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bomberman

# Build rule for target.
bomberman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bomberman
.PHONY : bomberman

# fast build rule for target.
bomberman/fast:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/build
.PHONY : bomberman/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/main.cpp.s
.PHONY : main.cpp.s

sources/BackgroundLoader.o: sources/BackgroundLoader.cpp.o

.PHONY : sources/BackgroundLoader.o

# target to build an object file
sources/BackgroundLoader.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/BackgroundLoader.cpp.o
.PHONY : sources/BackgroundLoader.cpp.o

sources/BackgroundLoader.i: sources/BackgroundLoader.cpp.i

.PHONY : sources/BackgroundLoader.i

# target to preprocess a source file
sources/BackgroundLoader.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/BackgroundLoader.cpp.i
.PHONY : sources/BackgroundLoader.cpp.i

sources/BackgroundLoader.s: sources/BackgroundLoader.cpp.s

.PHONY : sources/BackgroundLoader.s

# target to generate assembly for a file
sources/BackgroundLoader.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/BackgroundLoader.cpp.s
.PHONY : sources/BackgroundLoader.cpp.s

sources/BomberWave.o: sources/BomberWave.cpp.o

.PHONY : sources/BomberWave.o

# target to build an object file
sources/BomberWave.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/BomberWave.cpp.o
.PHONY : sources/BomberWave.cpp.o

sources/BomberWave.i: sources/BomberWave.cpp.i

.PHONY : sources/BomberWave.i

# target to preprocess a source file
sources/BomberWave.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/BomberWave.cpp.i
.PHONY : sources/BomberWave.cpp.i

sources/BomberWave.s: sources/BomberWave.cpp.s

.PHONY : sources/BomberWave.s

# target to generate assembly for a file
sources/BomberWave.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/BomberWave.cpp.s
.PHONY : sources/BomberWave.cpp.s

sources/Exceptions.o: sources/Exceptions.cpp.o

.PHONY : sources/Exceptions.o

# target to build an object file
sources/Exceptions.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/Exceptions.cpp.o
.PHONY : sources/Exceptions.cpp.o

sources/Exceptions.i: sources/Exceptions.cpp.i

.PHONY : sources/Exceptions.i

# target to preprocess a source file
sources/Exceptions.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/Exceptions.cpp.i
.PHONY : sources/Exceptions.cpp.i

sources/Exceptions.s: sources/Exceptions.cpp.s

.PHONY : sources/Exceptions.s

# target to generate assembly for a file
sources/Exceptions.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/Exceptions.cpp.s
.PHONY : sources/Exceptions.cpp.s

sources/GameInputManager.o: sources/GameInputManager.cpp.o

.PHONY : sources/GameInputManager.o

# target to build an object file
sources/GameInputManager.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameInputManager.cpp.o
.PHONY : sources/GameInputManager.cpp.o

sources/GameInputManager.i: sources/GameInputManager.cpp.i

.PHONY : sources/GameInputManager.i

# target to preprocess a source file
sources/GameInputManager.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameInputManager.cpp.i
.PHONY : sources/GameInputManager.cpp.i

sources/GameInputManager.s: sources/GameInputManager.cpp.s

.PHONY : sources/GameInputManager.s

# target to generate assembly for a file
sources/GameInputManager.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameInputManager.cpp.s
.PHONY : sources/GameInputManager.cpp.s

sources/GameManager.o: sources/GameManager.cpp.o

.PHONY : sources/GameManager.o

# target to build an object file
sources/GameManager.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameManager.cpp.o
.PHONY : sources/GameManager.cpp.o

sources/GameManager.i: sources/GameManager.cpp.i

.PHONY : sources/GameManager.i

# target to preprocess a source file
sources/GameManager.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameManager.cpp.i
.PHONY : sources/GameManager.cpp.i

sources/GameManager.s: sources/GameManager.cpp.s

.PHONY : sources/GameManager.s

# target to generate assembly for a file
sources/GameManager.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameManager.cpp.s
.PHONY : sources/GameManager.cpp.s

sources/GameMap.o: sources/GameMap.cpp.o

.PHONY : sources/GameMap.o

# target to build an object file
sources/GameMap.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameMap.cpp.o
.PHONY : sources/GameMap.cpp.o

sources/GameMap.i: sources/GameMap.cpp.i

.PHONY : sources/GameMap.i

# target to preprocess a source file
sources/GameMap.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameMap.cpp.i
.PHONY : sources/GameMap.cpp.i

sources/GameMap.s: sources/GameMap.cpp.s

.PHONY : sources/GameMap.s

# target to generate assembly for a file
sources/GameMap.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameMap.cpp.s
.PHONY : sources/GameMap.cpp.s

sources/GameMapFactory.o: sources/GameMapFactory.cpp.o

.PHONY : sources/GameMapFactory.o

# target to build an object file
sources/GameMapFactory.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameMapFactory.cpp.o
.PHONY : sources/GameMapFactory.cpp.o

sources/GameMapFactory.i: sources/GameMapFactory.cpp.i

.PHONY : sources/GameMapFactory.i

# target to preprocess a source file
sources/GameMapFactory.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameMapFactory.cpp.i
.PHONY : sources/GameMapFactory.cpp.i

sources/GameMapFactory.s: sources/GameMapFactory.cpp.s

.PHONY : sources/GameMapFactory.s

# target to generate assembly for a file
sources/GameMapFactory.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameMapFactory.cpp.s
.PHONY : sources/GameMapFactory.cpp.s

sources/GameObjects/Bomb.o: sources/GameObjects/Bomb.cpp.o

.PHONY : sources/GameObjects/Bomb.o

# target to build an object file
sources/GameObjects/Bomb.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/Bomb.cpp.o
.PHONY : sources/GameObjects/Bomb.cpp.o

sources/GameObjects/Bomb.i: sources/GameObjects/Bomb.cpp.i

.PHONY : sources/GameObjects/Bomb.i

# target to preprocess a source file
sources/GameObjects/Bomb.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/Bomb.cpp.i
.PHONY : sources/GameObjects/Bomb.cpp.i

sources/GameObjects/Bomb.s: sources/GameObjects/Bomb.cpp.s

.PHONY : sources/GameObjects/Bomb.s

# target to generate assembly for a file
sources/GameObjects/Bomb.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/Bomb.cpp.s
.PHONY : sources/GameObjects/Bomb.cpp.s

sources/GameObjects/Explosion.o: sources/GameObjects/Explosion.cpp.o

.PHONY : sources/GameObjects/Explosion.o

# target to build an object file
sources/GameObjects/Explosion.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/Explosion.cpp.o
.PHONY : sources/GameObjects/Explosion.cpp.o

sources/GameObjects/Explosion.i: sources/GameObjects/Explosion.cpp.i

.PHONY : sources/GameObjects/Explosion.i

# target to preprocess a source file
sources/GameObjects/Explosion.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/Explosion.cpp.i
.PHONY : sources/GameObjects/Explosion.cpp.i

sources/GameObjects/Explosion.s: sources/GameObjects/Explosion.cpp.s

.PHONY : sources/GameObjects/Explosion.s

# target to generate assembly for a file
sources/GameObjects/Explosion.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/Explosion.cpp.s
.PHONY : sources/GameObjects/Explosion.cpp.s

sources/GameObjects/GameObject.o: sources/GameObjects/GameObject.cpp.o

.PHONY : sources/GameObjects/GameObject.o

# target to build an object file
sources/GameObjects/GameObject.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/GameObject.cpp.o
.PHONY : sources/GameObjects/GameObject.cpp.o

sources/GameObjects/GameObject.i: sources/GameObjects/GameObject.cpp.i

.PHONY : sources/GameObjects/GameObject.i

# target to preprocess a source file
sources/GameObjects/GameObject.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/GameObject.cpp.i
.PHONY : sources/GameObjects/GameObject.cpp.i

sources/GameObjects/GameObject.s: sources/GameObjects/GameObject.cpp.s

.PHONY : sources/GameObjects/GameObject.s

# target to generate assembly for a file
sources/GameObjects/GameObject.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/GameObject.cpp.s
.PHONY : sources/GameObjects/GameObject.cpp.s

sources/GameObjects/Monster.o: sources/GameObjects/Monster.cpp.o

.PHONY : sources/GameObjects/Monster.o

# target to build an object file
sources/GameObjects/Monster.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/Monster.cpp.o
.PHONY : sources/GameObjects/Monster.cpp.o

sources/GameObjects/Monster.i: sources/GameObjects/Monster.cpp.i

.PHONY : sources/GameObjects/Monster.i

# target to preprocess a source file
sources/GameObjects/Monster.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/Monster.cpp.i
.PHONY : sources/GameObjects/Monster.cpp.i

sources/GameObjects/Monster.s: sources/GameObjects/Monster.cpp.s

.PHONY : sources/GameObjects/Monster.s

# target to generate assembly for a file
sources/GameObjects/Monster.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/Monster.cpp.s
.PHONY : sources/GameObjects/Monster.cpp.s

sources/GameObjects/Player.o: sources/GameObjects/Player.cpp.o

.PHONY : sources/GameObjects/Player.o

# target to build an object file
sources/GameObjects/Player.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/Player.cpp.o
.PHONY : sources/GameObjects/Player.cpp.o

sources/GameObjects/Player.i: sources/GameObjects/Player.cpp.i

.PHONY : sources/GameObjects/Player.i

# target to preprocess a source file
sources/GameObjects/Player.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/Player.cpp.i
.PHONY : sources/GameObjects/Player.cpp.i

sources/GameObjects/Player.s: sources/GameObjects/Player.cpp.s

.PHONY : sources/GameObjects/Player.s

# target to generate assembly for a file
sources/GameObjects/Player.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/Player.cpp.s
.PHONY : sources/GameObjects/Player.cpp.s

sources/GameObjects/PowerUps.o: sources/GameObjects/PowerUps.cpp.o

.PHONY : sources/GameObjects/PowerUps.o

# target to build an object file
sources/GameObjects/PowerUps.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/PowerUps.cpp.o
.PHONY : sources/GameObjects/PowerUps.cpp.o

sources/GameObjects/PowerUps.i: sources/GameObjects/PowerUps.cpp.i

.PHONY : sources/GameObjects/PowerUps.i

# target to preprocess a source file
sources/GameObjects/PowerUps.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/PowerUps.cpp.i
.PHONY : sources/GameObjects/PowerUps.cpp.i

sources/GameObjects/PowerUps.s: sources/GameObjects/PowerUps.cpp.s

.PHONY : sources/GameObjects/PowerUps.s

# target to generate assembly for a file
sources/GameObjects/PowerUps.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/PowerUps.cpp.s
.PHONY : sources/GameObjects/PowerUps.cpp.s

sources/GameObjects/Test.o: sources/GameObjects/Test.cpp.o

.PHONY : sources/GameObjects/Test.o

# target to build an object file
sources/GameObjects/Test.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/Test.cpp.o
.PHONY : sources/GameObjects/Test.cpp.o

sources/GameObjects/Test.i: sources/GameObjects/Test.cpp.i

.PHONY : sources/GameObjects/Test.i

# target to preprocess a source file
sources/GameObjects/Test.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/Test.cpp.i
.PHONY : sources/GameObjects/Test.cpp.i

sources/GameObjects/Test.s: sources/GameObjects/Test.cpp.s

.PHONY : sources/GameObjects/Test.s

# target to generate assembly for a file
sources/GameObjects/Test.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/Test.cpp.s
.PHONY : sources/GameObjects/Test.cpp.s

sources/GameObjects/Walls.o: sources/GameObjects/Walls.cpp.o

.PHONY : sources/GameObjects/Walls.o

# target to build an object file
sources/GameObjects/Walls.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/Walls.cpp.o
.PHONY : sources/GameObjects/Walls.cpp.o

sources/GameObjects/Walls.i: sources/GameObjects/Walls.cpp.i

.PHONY : sources/GameObjects/Walls.i

# target to preprocess a source file
sources/GameObjects/Walls.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/Walls.cpp.i
.PHONY : sources/GameObjects/Walls.cpp.i

sources/GameObjects/Walls.s: sources/GameObjects/Walls.cpp.s

.PHONY : sources/GameObjects/Walls.s

# target to generate assembly for a file
sources/GameObjects/Walls.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameObjects/Walls.cpp.s
.PHONY : sources/GameObjects/Walls.cpp.s

sources/GameRenderer.o: sources/GameRenderer.cpp.o

.PHONY : sources/GameRenderer.o

# target to build an object file
sources/GameRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameRenderer.cpp.o
.PHONY : sources/GameRenderer.cpp.o

sources/GameRenderer.i: sources/GameRenderer.cpp.i

.PHONY : sources/GameRenderer.i

# target to preprocess a source file
sources/GameRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameRenderer.cpp.i
.PHONY : sources/GameRenderer.cpp.i

sources/GameRenderer.s: sources/GameRenderer.cpp.s

.PHONY : sources/GameRenderer.s

# target to generate assembly for a file
sources/GameRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameRenderer.cpp.s
.PHONY : sources/GameRenderer.cpp.s

sources/GameTime.o: sources/GameTime.cpp.o

.PHONY : sources/GameTime.o

# target to build an object file
sources/GameTime.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameTime.cpp.o
.PHONY : sources/GameTime.cpp.o

sources/GameTime.i: sources/GameTime.cpp.i

.PHONY : sources/GameTime.i

# target to preprocess a source file
sources/GameTime.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameTime.cpp.i
.PHONY : sources/GameTime.cpp.i

sources/GameTime.s: sources/GameTime.cpp.s

.PHONY : sources/GameTime.s

# target to generate assembly for a file
sources/GameTime.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameTime.cpp.s
.PHONY : sources/GameTime.cpp.s

sources/GameUIManager.o: sources/GameUIManager.cpp.o

.PHONY : sources/GameUIManager.o

# target to build an object file
sources/GameUIManager.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameUIManager.cpp.o
.PHONY : sources/GameUIManager.cpp.o

sources/GameUIManager.i: sources/GameUIManager.cpp.i

.PHONY : sources/GameUIManager.i

# target to preprocess a source file
sources/GameUIManager.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameUIManager.cpp.i
.PHONY : sources/GameUIManager.cpp.i

sources/GameUIManager.s: sources/GameUIManager.cpp.s

.PHONY : sources/GameUIManager.s

# target to generate assembly for a file
sources/GameUIManager.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameUIManager.cpp.s
.PHONY : sources/GameUIManager.cpp.s

sources/GameUtils.o: sources/GameUtils.cpp.o

.PHONY : sources/GameUtils.o

# target to build an object file
sources/GameUtils.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameUtils.cpp.o
.PHONY : sources/GameUtils.cpp.o

sources/GameUtils.i: sources/GameUtils.cpp.i

.PHONY : sources/GameUtils.i

# target to preprocess a source file
sources/GameUtils.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameUtils.cpp.i
.PHONY : sources/GameUtils.cpp.i

sources/GameUtils.s: sources/GameUtils.cpp.s

.PHONY : sources/GameUtils.s

# target to generate assembly for a file
sources/GameUtils.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/GameUtils.cpp.s
.PHONY : sources/GameUtils.cpp.s

sources/MainMenu.o: sources/MainMenu.cpp.o

.PHONY : sources/MainMenu.o

# target to build an object file
sources/MainMenu.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/MainMenu.cpp.o
.PHONY : sources/MainMenu.cpp.o

sources/MainMenu.i: sources/MainMenu.cpp.i

.PHONY : sources/MainMenu.i

# target to preprocess a source file
sources/MainMenu.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/MainMenu.cpp.i
.PHONY : sources/MainMenu.cpp.i

sources/MainMenu.s: sources/MainMenu.cpp.s

.PHONY : sources/MainMenu.s

# target to generate assembly for a file
sources/MainMenu.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/MainMenu.cpp.s
.PHONY : sources/MainMenu.cpp.s

sources/PlayerBuff.o: sources/PlayerBuff.cpp.o

.PHONY : sources/PlayerBuff.o

# target to build an object file
sources/PlayerBuff.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/PlayerBuff.cpp.o
.PHONY : sources/PlayerBuff.cpp.o

sources/PlayerBuff.i: sources/PlayerBuff.cpp.i

.PHONY : sources/PlayerBuff.i

# target to preprocess a source file
sources/PlayerBuff.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/PlayerBuff.cpp.i
.PHONY : sources/PlayerBuff.cpp.i

sources/PlayerBuff.s: sources/PlayerBuff.cpp.s

.PHONY : sources/PlayerBuff.s

# target to generate assembly for a file
sources/PlayerBuff.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/PlayerBuff.cpp.s
.PHONY : sources/PlayerBuff.cpp.s

sources/gameclient/GameSession.o: sources/gameclient/GameSession.cpp.o

.PHONY : sources/gameclient/GameSession.o

# target to build an object file
sources/gameclient/GameSession.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameclient/GameSession.cpp.o
.PHONY : sources/gameclient/GameSession.cpp.o

sources/gameclient/GameSession.i: sources/gameclient/GameSession.cpp.i

.PHONY : sources/gameclient/GameSession.i

# target to preprocess a source file
sources/gameclient/GameSession.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameclient/GameSession.cpp.i
.PHONY : sources/gameclient/GameSession.cpp.i

sources/gameclient/GameSession.s: sources/gameclient/GameSession.cpp.s

.PHONY : sources/gameclient/GameSession.s

# target to generate assembly for a file
sources/gameclient/GameSession.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameclient/GameSession.cpp.s
.PHONY : sources/gameclient/GameSession.cpp.s

sources/gameclient/GameSessionConnector.o: sources/gameclient/GameSessionConnector.cpp.o

.PHONY : sources/gameclient/GameSessionConnector.o

# target to build an object file
sources/gameclient/GameSessionConnector.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameclient/GameSessionConnector.cpp.o
.PHONY : sources/gameclient/GameSessionConnector.cpp.o

sources/gameclient/GameSessionConnector.i: sources/gameclient/GameSessionConnector.cpp.i

.PHONY : sources/gameclient/GameSessionConnector.i

# target to preprocess a source file
sources/gameclient/GameSessionConnector.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameclient/GameSessionConnector.cpp.i
.PHONY : sources/gameclient/GameSessionConnector.cpp.i

sources/gameclient/GameSessionConnector.s: sources/gameclient/GameSessionConnector.cpp.s

.PHONY : sources/gameclient/GameSessionConnector.s

# target to generate assembly for a file
sources/gameclient/GameSessionConnector.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameclient/GameSessionConnector.cpp.s
.PHONY : sources/gameclient/GameSessionConnector.cpp.s

sources/gameclient/GameSessionController.o: sources/gameclient/GameSessionController.cpp.o

.PHONY : sources/gameclient/GameSessionController.o

# target to build an object file
sources/gameclient/GameSessionController.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameclient/GameSessionController.cpp.o
.PHONY : sources/gameclient/GameSessionController.cpp.o

sources/gameclient/GameSessionController.i: sources/gameclient/GameSessionController.cpp.i

.PHONY : sources/gameclient/GameSessionController.i

# target to preprocess a source file
sources/gameclient/GameSessionController.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameclient/GameSessionController.cpp.i
.PHONY : sources/gameclient/GameSessionController.cpp.i

sources/gameclient/GameSessionController.s: sources/gameclient/GameSessionController.cpp.s

.PHONY : sources/gameclient/GameSessionController.s

# target to generate assembly for a file
sources/gameclient/GameSessionController.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameclient/GameSessionController.cpp.s
.PHONY : sources/gameclient/GameSessionController.cpp.s

sources/gameclient/GameSessionHandler.o: sources/gameclient/GameSessionHandler.cpp.o

.PHONY : sources/gameclient/GameSessionHandler.o

# target to build an object file
sources/gameclient/GameSessionHandler.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameclient/GameSessionHandler.cpp.o
.PHONY : sources/gameclient/GameSessionHandler.cpp.o

sources/gameclient/GameSessionHandler.i: sources/gameclient/GameSessionHandler.cpp.i

.PHONY : sources/gameclient/GameSessionHandler.i

# target to preprocess a source file
sources/gameclient/GameSessionHandler.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameclient/GameSessionHandler.cpp.i
.PHONY : sources/gameclient/GameSessionHandler.cpp.i

sources/gameclient/GameSessionHandler.s: sources/gameclient/GameSessionHandler.cpp.s

.PHONY : sources/gameclient/GameSessionHandler.s

# target to generate assembly for a file
sources/gameclient/GameSessionHandler.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameclient/GameSessionHandler.cpp.s
.PHONY : sources/gameclient/GameSessionHandler.cpp.s

sources/gameserver/GameClient.o: sources/gameserver/GameClient.cpp.o

.PHONY : sources/gameserver/GameClient.o

# target to build an object file
sources/gameserver/GameClient.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameserver/GameClient.cpp.o
.PHONY : sources/gameserver/GameClient.cpp.o

sources/gameserver/GameClient.i: sources/gameserver/GameClient.cpp.i

.PHONY : sources/gameserver/GameClient.i

# target to preprocess a source file
sources/gameserver/GameClient.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameserver/GameClient.cpp.i
.PHONY : sources/gameserver/GameClient.cpp.i

sources/gameserver/GameClient.s: sources/gameserver/GameClient.cpp.s

.PHONY : sources/gameserver/GameClient.s

# target to generate assembly for a file
sources/gameserver/GameClient.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameserver/GameClient.cpp.s
.PHONY : sources/gameserver/GameClient.cpp.s

sources/gameserver/GameClientHandler.o: sources/gameserver/GameClientHandler.cpp.o

.PHONY : sources/gameserver/GameClientHandler.o

# target to build an object file
sources/gameserver/GameClientHandler.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameserver/GameClientHandler.cpp.o
.PHONY : sources/gameserver/GameClientHandler.cpp.o

sources/gameserver/GameClientHandler.i: sources/gameserver/GameClientHandler.cpp.i

.PHONY : sources/gameserver/GameClientHandler.i

# target to preprocess a source file
sources/gameserver/GameClientHandler.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameserver/GameClientHandler.cpp.i
.PHONY : sources/gameserver/GameClientHandler.cpp.i

sources/gameserver/GameClientHandler.s: sources/gameserver/GameClientHandler.cpp.s

.PHONY : sources/gameserver/GameClientHandler.s

# target to generate assembly for a file
sources/gameserver/GameClientHandler.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameserver/GameClientHandler.cpp.s
.PHONY : sources/gameserver/GameClientHandler.cpp.s

sources/gameserver/GameServer.o: sources/gameserver/GameServer.cpp.o

.PHONY : sources/gameserver/GameServer.o

# target to build an object file
sources/gameserver/GameServer.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameserver/GameServer.cpp.o
.PHONY : sources/gameserver/GameServer.cpp.o

sources/gameserver/GameServer.i: sources/gameserver/GameServer.cpp.i

.PHONY : sources/gameserver/GameServer.i

# target to preprocess a source file
sources/gameserver/GameServer.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameserver/GameServer.cpp.i
.PHONY : sources/gameserver/GameServer.cpp.i

sources/gameserver/GameServer.s: sources/gameserver/GameServer.cpp.s

.PHONY : sources/gameserver/GameServer.s

# target to generate assembly for a file
sources/gameserver/GameServer.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameserver/GameServer.cpp.s
.PHONY : sources/gameserver/GameServer.cpp.s

sources/gameserver/GameServerController.o: sources/gameserver/GameServerController.cpp.o

.PHONY : sources/gameserver/GameServerController.o

# target to build an object file
sources/gameserver/GameServerController.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameserver/GameServerController.cpp.o
.PHONY : sources/gameserver/GameServerController.cpp.o

sources/gameserver/GameServerController.i: sources/gameserver/GameServerController.cpp.i

.PHONY : sources/gameserver/GameServerController.i

# target to preprocess a source file
sources/gameserver/GameServerController.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameserver/GameServerController.cpp.i
.PHONY : sources/gameserver/GameServerController.cpp.i

sources/gameserver/GameServerController.s: sources/gameserver/GameServerController.cpp.s

.PHONY : sources/gameserver/GameServerController.s

# target to generate assembly for a file
sources/gameserver/GameServerController.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/gameserver/GameServerController.cpp.s
.PHONY : sources/gameserver/GameServerController.cpp.s

sources/network/ANetworkClient.o: sources/network/ANetworkClient.cpp.o

.PHONY : sources/network/ANetworkClient.o

# target to build an object file
sources/network/ANetworkClient.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/network/ANetworkClient.cpp.o
.PHONY : sources/network/ANetworkClient.cpp.o

sources/network/ANetworkClient.i: sources/network/ANetworkClient.cpp.i

.PHONY : sources/network/ANetworkClient.i

# target to preprocess a source file
sources/network/ANetworkClient.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/network/ANetworkClient.cpp.i
.PHONY : sources/network/ANetworkClient.cpp.i

sources/network/ANetworkClient.s: sources/network/ANetworkClient.cpp.s

.PHONY : sources/network/ANetworkClient.s

# target to generate assembly for a file
sources/network/ANetworkClient.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/network/ANetworkClient.cpp.s
.PHONY : sources/network/ANetworkClient.cpp.s

sources/network/ANetworkController.o: sources/network/ANetworkController.cpp.o

.PHONY : sources/network/ANetworkController.o

# target to build an object file
sources/network/ANetworkController.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/network/ANetworkController.cpp.o
.PHONY : sources/network/ANetworkController.cpp.o

sources/network/ANetworkController.i: sources/network/ANetworkController.cpp.i

.PHONY : sources/network/ANetworkController.i

# target to preprocess a source file
sources/network/ANetworkController.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/network/ANetworkController.cpp.i
.PHONY : sources/network/ANetworkController.cpp.i

sources/network/ANetworkController.s: sources/network/ANetworkController.cpp.s

.PHONY : sources/network/ANetworkController.s

# target to generate assembly for a file
sources/network/ANetworkController.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/network/ANetworkController.cpp.s
.PHONY : sources/network/ANetworkController.cpp.s

sources/network/NetworkClientAdapter.o: sources/network/NetworkClientAdapter.cpp.o

.PHONY : sources/network/NetworkClientAdapter.o

# target to build an object file
sources/network/NetworkClientAdapter.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/network/NetworkClientAdapter.cpp.o
.PHONY : sources/network/NetworkClientAdapter.cpp.o

sources/network/NetworkClientAdapter.i: sources/network/NetworkClientAdapter.cpp.i

.PHONY : sources/network/NetworkClientAdapter.i

# target to preprocess a source file
sources/network/NetworkClientAdapter.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/network/NetworkClientAdapter.cpp.i
.PHONY : sources/network/NetworkClientAdapter.cpp.i

sources/network/NetworkClientAdapter.s: sources/network/NetworkClientAdapter.cpp.s

.PHONY : sources/network/NetworkClientAdapter.s

# target to generate assembly for a file
sources/network/NetworkClientAdapter.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/network/NetworkClientAdapter.cpp.s
.PHONY : sources/network/NetworkClientAdapter.cpp.s

sources/network/NetworkProtocol.o: sources/network/NetworkProtocol.cpp.o

.PHONY : sources/network/NetworkProtocol.o

# target to build an object file
sources/network/NetworkProtocol.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/network/NetworkProtocol.cpp.o
.PHONY : sources/network/NetworkProtocol.cpp.o

sources/network/NetworkProtocol.i: sources/network/NetworkProtocol.cpp.i

.PHONY : sources/network/NetworkProtocol.i

# target to preprocess a source file
sources/network/NetworkProtocol.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/network/NetworkProtocol.cpp.i
.PHONY : sources/network/NetworkProtocol.cpp.i

sources/network/NetworkProtocol.s: sources/network/NetworkProtocol.cpp.s

.PHONY : sources/network/NetworkProtocol.s

# target to generate assembly for a file
sources/network/NetworkProtocol.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/network/NetworkProtocol.cpp.s
.PHONY : sources/network/NetworkProtocol.cpp.s

sources/protocol/HelloConnectMessage.o: sources/protocol/HelloConnectMessage.cpp.o

.PHONY : sources/protocol/HelloConnectMessage.o

# target to build an object file
sources/protocol/HelloConnectMessage.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/protocol/HelloConnectMessage.cpp.o
.PHONY : sources/protocol/HelloConnectMessage.cpp.o

sources/protocol/HelloConnectMessage.i: sources/protocol/HelloConnectMessage.cpp.i

.PHONY : sources/protocol/HelloConnectMessage.i

# target to preprocess a source file
sources/protocol/HelloConnectMessage.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/protocol/HelloConnectMessage.cpp.i
.PHONY : sources/protocol/HelloConnectMessage.cpp.i

sources/protocol/HelloConnectMessage.s: sources/protocol/HelloConnectMessage.cpp.s

.PHONY : sources/protocol/HelloConnectMessage.s

# target to generate assembly for a file
sources/protocol/HelloConnectMessage.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/protocol/HelloConnectMessage.cpp.s
.PHONY : sources/protocol/HelloConnectMessage.cpp.s

sources/protocol/MapDataMessage.o: sources/protocol/MapDataMessage.cpp.o

.PHONY : sources/protocol/MapDataMessage.o

# target to build an object file
sources/protocol/MapDataMessage.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/protocol/MapDataMessage.cpp.o
.PHONY : sources/protocol/MapDataMessage.cpp.o

sources/protocol/MapDataMessage.i: sources/protocol/MapDataMessage.cpp.i

.PHONY : sources/protocol/MapDataMessage.i

# target to preprocess a source file
sources/protocol/MapDataMessage.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/protocol/MapDataMessage.cpp.i
.PHONY : sources/protocol/MapDataMessage.cpp.i

sources/protocol/MapDataMessage.s: sources/protocol/MapDataMessage.cpp.s

.PHONY : sources/protocol/MapDataMessage.s

# target to generate assembly for a file
sources/protocol/MapDataMessage.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/protocol/MapDataMessage.cpp.s
.PHONY : sources/protocol/MapDataMessage.cpp.s

sources/serializable/BinaryDataReader.o: sources/serializable/BinaryDataReader.cpp.o

.PHONY : sources/serializable/BinaryDataReader.o

# target to build an object file
sources/serializable/BinaryDataReader.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/serializable/BinaryDataReader.cpp.o
.PHONY : sources/serializable/BinaryDataReader.cpp.o

sources/serializable/BinaryDataReader.i: sources/serializable/BinaryDataReader.cpp.i

.PHONY : sources/serializable/BinaryDataReader.i

# target to preprocess a source file
sources/serializable/BinaryDataReader.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/serializable/BinaryDataReader.cpp.i
.PHONY : sources/serializable/BinaryDataReader.cpp.i

sources/serializable/BinaryDataReader.s: sources/serializable/BinaryDataReader.cpp.s

.PHONY : sources/serializable/BinaryDataReader.s

# target to generate assembly for a file
sources/serializable/BinaryDataReader.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/serializable/BinaryDataReader.cpp.s
.PHONY : sources/serializable/BinaryDataReader.cpp.s

sources/serializable/BinaryDataWriter.o: sources/serializable/BinaryDataWriter.cpp.o

.PHONY : sources/serializable/BinaryDataWriter.o

# target to build an object file
sources/serializable/BinaryDataWriter.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/serializable/BinaryDataWriter.cpp.o
.PHONY : sources/serializable/BinaryDataWriter.cpp.o

sources/serializable/BinaryDataWriter.i: sources/serializable/BinaryDataWriter.cpp.i

.PHONY : sources/serializable/BinaryDataWriter.i

# target to preprocess a source file
sources/serializable/BinaryDataWriter.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/serializable/BinaryDataWriter.cpp.i
.PHONY : sources/serializable/BinaryDataWriter.cpp.i

sources/serializable/BinaryDataWriter.s: sources/serializable/BinaryDataWriter.cpp.s

.PHONY : sources/serializable/BinaryDataWriter.s

# target to generate assembly for a file
sources/serializable/BinaryDataWriter.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/serializable/BinaryDataWriter.cpp.s
.PHONY : sources/serializable/BinaryDataWriter.cpp.s

sources/serializable/GameDataSerializer.o: sources/serializable/GameDataSerializer.cpp.o

.PHONY : sources/serializable/GameDataSerializer.o

# target to build an object file
sources/serializable/GameDataSerializer.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/serializable/GameDataSerializer.cpp.o
.PHONY : sources/serializable/GameDataSerializer.cpp.o

sources/serializable/GameDataSerializer.i: sources/serializable/GameDataSerializer.cpp.i

.PHONY : sources/serializable/GameDataSerializer.i

# target to preprocess a source file
sources/serializable/GameDataSerializer.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/serializable/GameDataSerializer.cpp.i
.PHONY : sources/serializable/GameDataSerializer.cpp.i

sources/serializable/GameDataSerializer.s: sources/serializable/GameDataSerializer.cpp.s

.PHONY : sources/serializable/GameDataSerializer.s

# target to generate assembly for a file
sources/serializable/GameDataSerializer.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/serializable/GameDataSerializer.cpp.s
.PHONY : sources/serializable/GameDataSerializer.cpp.s

sources/shared/ANetworkAsyncListener.o: sources/shared/ANetworkAsyncListener.cpp.o

.PHONY : sources/shared/ANetworkAsyncListener.o

# target to build an object file
sources/shared/ANetworkAsyncListener.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/shared/ANetworkAsyncListener.cpp.o
.PHONY : sources/shared/ANetworkAsyncListener.cpp.o

sources/shared/ANetworkAsyncListener.i: sources/shared/ANetworkAsyncListener.cpp.i

.PHONY : sources/shared/ANetworkAsyncListener.i

# target to preprocess a source file
sources/shared/ANetworkAsyncListener.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/shared/ANetworkAsyncListener.cpp.i
.PHONY : sources/shared/ANetworkAsyncListener.cpp.i

sources/shared/ANetworkAsyncListener.s: sources/shared/ANetworkAsyncListener.cpp.s

.PHONY : sources/shared/ANetworkAsyncListener.s

# target to generate assembly for a file
sources/shared/ANetworkAsyncListener.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/shared/ANetworkAsyncListener.cpp.s
.PHONY : sources/shared/ANetworkAsyncListener.cpp.s

sources/shared/ANetworkAsyncServer.o: sources/shared/ANetworkAsyncServer.cpp.o

.PHONY : sources/shared/ANetworkAsyncServer.o

# target to build an object file
sources/shared/ANetworkAsyncServer.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/shared/ANetworkAsyncServer.cpp.o
.PHONY : sources/shared/ANetworkAsyncServer.cpp.o

sources/shared/ANetworkAsyncServer.i: sources/shared/ANetworkAsyncServer.cpp.i

.PHONY : sources/shared/ANetworkAsyncServer.i

# target to preprocess a source file
sources/shared/ANetworkAsyncServer.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/shared/ANetworkAsyncServer.cpp.i
.PHONY : sources/shared/ANetworkAsyncServer.cpp.i

sources/shared/ANetworkAsyncServer.s: sources/shared/ANetworkAsyncServer.cpp.s

.PHONY : sources/shared/ANetworkAsyncServer.s

# target to generate assembly for a file
sources/shared/ANetworkAsyncServer.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/shared/ANetworkAsyncServer.cpp.s
.PHONY : sources/shared/ANetworkAsyncServer.cpp.s

sources/shared/ANetworkBuffer.o: sources/shared/ANetworkBuffer.cpp.o

.PHONY : sources/shared/ANetworkBuffer.o

# target to build an object file
sources/shared/ANetworkBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/shared/ANetworkBuffer.cpp.o
.PHONY : sources/shared/ANetworkBuffer.cpp.o

sources/shared/ANetworkBuffer.i: sources/shared/ANetworkBuffer.cpp.i

.PHONY : sources/shared/ANetworkBuffer.i

# target to preprocess a source file
sources/shared/ANetworkBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/shared/ANetworkBuffer.cpp.i
.PHONY : sources/shared/ANetworkBuffer.cpp.i

sources/shared/ANetworkBuffer.s: sources/shared/ANetworkBuffer.cpp.s

.PHONY : sources/shared/ANetworkBuffer.s

# target to generate assembly for a file
sources/shared/ANetworkBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/shared/ANetworkBuffer.cpp.s
.PHONY : sources/shared/ANetworkBuffer.cpp.s

sources/shared/ANetworkClientAdapter.o: sources/shared/ANetworkClientAdapter.cpp.o

.PHONY : sources/shared/ANetworkClientAdapter.o

# target to build an object file
sources/shared/ANetworkClientAdapter.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/shared/ANetworkClientAdapter.cpp.o
.PHONY : sources/shared/ANetworkClientAdapter.cpp.o

sources/shared/ANetworkClientAdapter.i: sources/shared/ANetworkClientAdapter.cpp.i

.PHONY : sources/shared/ANetworkClientAdapter.i

# target to preprocess a source file
sources/shared/ANetworkClientAdapter.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/shared/ANetworkClientAdapter.cpp.i
.PHONY : sources/shared/ANetworkClientAdapter.cpp.i

sources/shared/ANetworkClientAdapter.s: sources/shared/ANetworkClientAdapter.cpp.s

.PHONY : sources/shared/ANetworkClientAdapter.s

# target to generate assembly for a file
sources/shared/ANetworkClientAdapter.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/shared/ANetworkClientAdapter.cpp.s
.PHONY : sources/shared/ANetworkClientAdapter.cpp.s

sources/shared/NetworkClient.o: sources/shared/NetworkClient.cpp.o

.PHONY : sources/shared/NetworkClient.o

# target to build an object file
sources/shared/NetworkClient.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/shared/NetworkClient.cpp.o
.PHONY : sources/shared/NetworkClient.cpp.o

sources/shared/NetworkClient.i: sources/shared/NetworkClient.cpp.i

.PHONY : sources/shared/NetworkClient.i

# target to preprocess a source file
sources/shared/NetworkClient.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/shared/NetworkClient.cpp.i
.PHONY : sources/shared/NetworkClient.cpp.i

sources/shared/NetworkClient.s: sources/shared/NetworkClient.cpp.s

.PHONY : sources/shared/NetworkClient.s

# target to generate assembly for a file
sources/shared/NetworkClient.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/shared/NetworkClient.cpp.s
.PHONY : sources/shared/NetworkClient.cpp.s

sources/shared/NetworkSocket.o: sources/shared/NetworkSocket.cpp.o

.PHONY : sources/shared/NetworkSocket.o

# target to build an object file
sources/shared/NetworkSocket.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/shared/NetworkSocket.cpp.o
.PHONY : sources/shared/NetworkSocket.cpp.o

sources/shared/NetworkSocket.i: sources/shared/NetworkSocket.cpp.i

.PHONY : sources/shared/NetworkSocket.i

# target to preprocess a source file
sources/shared/NetworkSocket.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/shared/NetworkSocket.cpp.i
.PHONY : sources/shared/NetworkSocket.cpp.i

sources/shared/NetworkSocket.s: sources/shared/NetworkSocket.cpp.s

.PHONY : sources/shared/NetworkSocket.s

# target to generate assembly for a file
sources/shared/NetworkSocket.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/shared/NetworkSocket.cpp.s
.PHONY : sources/shared/NetworkSocket.cpp.s

sources/shared/impl/BasicNetworkBuffer.o: sources/shared/impl/BasicNetworkBuffer.cpp.o

.PHONY : sources/shared/impl/BasicNetworkBuffer.o

# target to build an object file
sources/shared/impl/BasicNetworkBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/shared/impl/BasicNetworkBuffer.cpp.o
.PHONY : sources/shared/impl/BasicNetworkBuffer.cpp.o

sources/shared/impl/BasicNetworkBuffer.i: sources/shared/impl/BasicNetworkBuffer.cpp.i

.PHONY : sources/shared/impl/BasicNetworkBuffer.i

# target to preprocess a source file
sources/shared/impl/BasicNetworkBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/shared/impl/BasicNetworkBuffer.cpp.i
.PHONY : sources/shared/impl/BasicNetworkBuffer.cpp.i

sources/shared/impl/BasicNetworkBuffer.s: sources/shared/impl/BasicNetworkBuffer.cpp.s

.PHONY : sources/shared/impl/BasicNetworkBuffer.s

# target to generate assembly for a file
sources/shared/impl/BasicNetworkBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/sources/shared/impl/BasicNetworkBuffer.cpp.s
.PHONY : sources/shared/impl/BasicNetworkBuffer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... bomberman"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... sources/BackgroundLoader.o"
	@echo "... sources/BackgroundLoader.i"
	@echo "... sources/BackgroundLoader.s"
	@echo "... sources/BomberWave.o"
	@echo "... sources/BomberWave.i"
	@echo "... sources/BomberWave.s"
	@echo "... sources/Exceptions.o"
	@echo "... sources/Exceptions.i"
	@echo "... sources/Exceptions.s"
	@echo "... sources/GameInputManager.o"
	@echo "... sources/GameInputManager.i"
	@echo "... sources/GameInputManager.s"
	@echo "... sources/GameManager.o"
	@echo "... sources/GameManager.i"
	@echo "... sources/GameManager.s"
	@echo "... sources/GameMap.o"
	@echo "... sources/GameMap.i"
	@echo "... sources/GameMap.s"
	@echo "... sources/GameMapFactory.o"
	@echo "... sources/GameMapFactory.i"
	@echo "... sources/GameMapFactory.s"
	@echo "... sources/GameObjects/Bomb.o"
	@echo "... sources/GameObjects/Bomb.i"
	@echo "... sources/GameObjects/Bomb.s"
	@echo "... sources/GameObjects/Explosion.o"
	@echo "... sources/GameObjects/Explosion.i"
	@echo "... sources/GameObjects/Explosion.s"
	@echo "... sources/GameObjects/GameObject.o"
	@echo "... sources/GameObjects/GameObject.i"
	@echo "... sources/GameObjects/GameObject.s"
	@echo "... sources/GameObjects/Monster.o"
	@echo "... sources/GameObjects/Monster.i"
	@echo "... sources/GameObjects/Monster.s"
	@echo "... sources/GameObjects/Player.o"
	@echo "... sources/GameObjects/Player.i"
	@echo "... sources/GameObjects/Player.s"
	@echo "... sources/GameObjects/PowerUps.o"
	@echo "... sources/GameObjects/PowerUps.i"
	@echo "... sources/GameObjects/PowerUps.s"
	@echo "... sources/GameObjects/Test.o"
	@echo "... sources/GameObjects/Test.i"
	@echo "... sources/GameObjects/Test.s"
	@echo "... sources/GameObjects/Walls.o"
	@echo "... sources/GameObjects/Walls.i"
	@echo "... sources/GameObjects/Walls.s"
	@echo "... sources/GameRenderer.o"
	@echo "... sources/GameRenderer.i"
	@echo "... sources/GameRenderer.s"
	@echo "... sources/GameTime.o"
	@echo "... sources/GameTime.i"
	@echo "... sources/GameTime.s"
	@echo "... sources/GameUIManager.o"
	@echo "... sources/GameUIManager.i"
	@echo "... sources/GameUIManager.s"
	@echo "... sources/GameUtils.o"
	@echo "... sources/GameUtils.i"
	@echo "... sources/GameUtils.s"
	@echo "... sources/MainMenu.o"
	@echo "... sources/MainMenu.i"
	@echo "... sources/MainMenu.s"
	@echo "... sources/PlayerBuff.o"
	@echo "... sources/PlayerBuff.i"
	@echo "... sources/PlayerBuff.s"
	@echo "... sources/gameclient/GameSession.o"
	@echo "... sources/gameclient/GameSession.i"
	@echo "... sources/gameclient/GameSession.s"
	@echo "... sources/gameclient/GameSessionConnector.o"
	@echo "... sources/gameclient/GameSessionConnector.i"
	@echo "... sources/gameclient/GameSessionConnector.s"
	@echo "... sources/gameclient/GameSessionController.o"
	@echo "... sources/gameclient/GameSessionController.i"
	@echo "... sources/gameclient/GameSessionController.s"
	@echo "... sources/gameclient/GameSessionHandler.o"
	@echo "... sources/gameclient/GameSessionHandler.i"
	@echo "... sources/gameclient/GameSessionHandler.s"
	@echo "... sources/gameserver/GameClient.o"
	@echo "... sources/gameserver/GameClient.i"
	@echo "... sources/gameserver/GameClient.s"
	@echo "... sources/gameserver/GameClientHandler.o"
	@echo "... sources/gameserver/GameClientHandler.i"
	@echo "... sources/gameserver/GameClientHandler.s"
	@echo "... sources/gameserver/GameServer.o"
	@echo "... sources/gameserver/GameServer.i"
	@echo "... sources/gameserver/GameServer.s"
	@echo "... sources/gameserver/GameServerController.o"
	@echo "... sources/gameserver/GameServerController.i"
	@echo "... sources/gameserver/GameServerController.s"
	@echo "... sources/network/ANetworkClient.o"
	@echo "... sources/network/ANetworkClient.i"
	@echo "... sources/network/ANetworkClient.s"
	@echo "... sources/network/ANetworkController.o"
	@echo "... sources/network/ANetworkController.i"
	@echo "... sources/network/ANetworkController.s"
	@echo "... sources/network/NetworkClientAdapter.o"
	@echo "... sources/network/NetworkClientAdapter.i"
	@echo "... sources/network/NetworkClientAdapter.s"
	@echo "... sources/network/NetworkProtocol.o"
	@echo "... sources/network/NetworkProtocol.i"
	@echo "... sources/network/NetworkProtocol.s"
	@echo "... sources/protocol/HelloConnectMessage.o"
	@echo "... sources/protocol/HelloConnectMessage.i"
	@echo "... sources/protocol/HelloConnectMessage.s"
	@echo "... sources/protocol/MapDataMessage.o"
	@echo "... sources/protocol/MapDataMessage.i"
	@echo "... sources/protocol/MapDataMessage.s"
	@echo "... sources/serializable/BinaryDataReader.o"
	@echo "... sources/serializable/BinaryDataReader.i"
	@echo "... sources/serializable/BinaryDataReader.s"
	@echo "... sources/serializable/BinaryDataWriter.o"
	@echo "... sources/serializable/BinaryDataWriter.i"
	@echo "... sources/serializable/BinaryDataWriter.s"
	@echo "... sources/serializable/GameDataSerializer.o"
	@echo "... sources/serializable/GameDataSerializer.i"
	@echo "... sources/serializable/GameDataSerializer.s"
	@echo "... sources/shared/ANetworkAsyncListener.o"
	@echo "... sources/shared/ANetworkAsyncListener.i"
	@echo "... sources/shared/ANetworkAsyncListener.s"
	@echo "... sources/shared/ANetworkAsyncServer.o"
	@echo "... sources/shared/ANetworkAsyncServer.i"
	@echo "... sources/shared/ANetworkAsyncServer.s"
	@echo "... sources/shared/ANetworkBuffer.o"
	@echo "... sources/shared/ANetworkBuffer.i"
	@echo "... sources/shared/ANetworkBuffer.s"
	@echo "... sources/shared/ANetworkClientAdapter.o"
	@echo "... sources/shared/ANetworkClientAdapter.i"
	@echo "... sources/shared/ANetworkClientAdapter.s"
	@echo "... sources/shared/NetworkClient.o"
	@echo "... sources/shared/NetworkClient.i"
	@echo "... sources/shared/NetworkClient.s"
	@echo "... sources/shared/NetworkSocket.o"
	@echo "... sources/shared/NetworkSocket.i"
	@echo "... sources/shared/NetworkSocket.s"
	@echo "... sources/shared/impl/BasicNetworkBuffer.o"
	@echo "... sources/shared/impl/BasicNetworkBuffer.i"
	@echo "... sources/shared/impl/BasicNetworkBuffer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

